[package]
name = "optra"
version = "0.1.0"
authors = ["Daniel Yule <daniel.yule@gmail.com>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_macros = "*"
log = "0.3"
rdiff = "^0.1.1"

[dev-dependencies]
env_logger = "0.3"
